---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: powerfulseal
  labels:
    app: powerfulseal
  name: powerfulseal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: powerfulseal
  name: powerfulseal
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - '*'
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
  resourceNames: ["powerfulseal"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: powerfulseal
  name: powerfulseal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: powerfulseal
subjects:
- kind: ServiceAccount
  name: powerfulseal
  namespace: powerfulseal
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: powerfulseal
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- powerfulseal
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
